name: transform_in_isolate
version: 0.1.2
environment:
  sdk: ">=2.12.0 <3.0.0"
description: Simple helper to run stream transformation through isolate
author: Ski <skyjur@gmail.com>
repository: https://github.com/skyjur/dart_transform_in_isolate
issue_tracker: https://github.com/skyjur/dart_transform_in_isolate/issues
homepage: https://github.com/skyjur/dart_transform_in_isolate
dependencies:
dev_dependencies:
  test:
